export const CHEM_TOPICS = [
  { id: "atoms", name: "Atoms & Elements", blurb: "Particles, elements, compounds." },
  { id: "bonding", name: "Bonding", blurb: "Ionic and covalent ideas." },
  { id: "reactions", name: "Chemical reactions", blurb: "Word equations and conservation of mass." },
];

export const CHEM_QUESTIONS = [
  {
    id: "c1",
    topic: "Atoms & Elements",
    prompt: "A substance made of only one type of atom is called an…",
    answer: "element",
    accepted: ["element", "an element"],
    choices: ["element", "compound", "mixture", "molecule"],
    explain: "Elements contain one type of atom. Compounds contain two or more elements chemically joined.",
  },
  {
    id: "c2",
    topic: "Atoms & Elements",
    prompt: "What number identifies an element on the periodic table?",
    answer: "atomic number",
    accepted: ["atomic number", "proton number", "the atomic number"],
    choices: ["atomic number", "mass number", "group number", "period number"],
    explain: "The atomic (proton) number is unique to each element.",
  },
  {
    id: "c3",
    topic: "Bonding",
    prompt: "Ionic bonding typically happens between…",
    answer: "a metal and a non-metal",
    accepted: ["a metal and a non-metal", "metal and non-metal", "metals and non-metals"],
    choices: ["a metal and a non-metal", "two metals", "two non-metals", "two noble gases"],
    explain: "Metals lose electrons, non-metals gain them, forming oppositely charged ions.",
  },
  {
    id: "c4",
    topic: "Bonding",
    prompt: "Covalent bonds are formed by…",
    answer: "sharing electrons",
    accepted: ["sharing electrons", "shared electrons", "sharing pairs of electrons"],
    choices: ["sharing electrons", "transferring electrons", "sharing protons", "losing neutrons"],
    explain: "Non-metals can share electron pairs to gain full outer shells.",
  },
  {
    id: "c5",
    topic: "Chemical reactions",
    prompt: "In a chemical reaction, mass is…",
    answer: "conserved",
    accepted: ["conserved", "conservation of mass", "kept the same"],
    choices: ["conserved", "destroyed", "created from nothing", "always reduced"],
    explain: "Atoms are rearranged, not created or destroyed.",
  },
  {
    id: "c6",
    topic: "Chemical reactions",
    prompt: "A substance that speeds up a reaction without being used up is a…",
    answer: "catalyst",
    accepted: ["catalyst", "a catalyst"],
    choices: ["catalyst", "reactant", "product", "solvent"],
    explain: "Catalysts provide an alternative pathway with lower activation energy.",
  },
  {
    id: "c7",
    topic: "Atoms & Elements",
    prompt: "Which particles are found in the nucleus of an atom?",
    answer: "protons and neutrons",
    accepted: ["protons and neutrons", "protons + neutrons"],
    choices: ["protons and neutrons", "electrons and protons", "only electrons", "only neutrons"],
    explain: "The nucleus contains protons and neutrons. Electrons occupy shells around it.",
  },
  {
    id: "c8",
    topic: "Chemical reactions",
    prompt: "The word equation for burning magnesium in oxygen starts: magnesium + oxygen →",
    answer: "magnesium oxide",
    accepted: ["magnesium oxide"],
    choices: ["magnesium oxide", "magnesium hydroxide", "water", "carbon dioxide"],
    explain: "A metal + oxygen typically forms a metal oxide.",
  },
];
