export const ENG_TOPICS = [
  { id: "narrative", name: "Narrative", blurb: "Voice, tense, and structure." },
  { id: "language", name: "Language techniques", blurb: "Imagery, metaphor, tone." },
  { id: "writing", name: "Writing", blurb: "Planning, paragraphs, and purpose." },
];

export const ENG_QUESTIONS = [
  {
    id: "e1",
    topic: "Narrative",
    prompt: "A story told using I and we is written in…",
    answer: "first person",
    accepted: ["first person", "first-person", "the first person"],
    choices: ["first person", "second person", "third person", "the passive"],
    explain: "First person places the narrator inside the events.",
  },
  {
    id: "e2",
    topic: "Narrative",
    prompt: "He walked to the river is written in…",
    answer: "third person",
    accepted: ["third person", "third-person"],
    choices: ["third person", "first person", "second person", "imperative"],
    explain: "Third person uses he, she, they, names.",
  },
  {
    id: "e3",
    topic: "Language techniques",
    prompt: "A comparison using like or as is a…",
    answer: "simile",
    accepted: ["simile", "a simile"],
    choices: ["simile", "metaphor", "alliteration", "hyperbole"],
    explain: "Simile: as quiet as snow. Metaphor says one thing is another.",
  },
  {
    id: "e4",
    topic: "Language techniques",
    prompt: "The moon was a silver coin is an example of…",
    answer: "metaphor",
    accepted: ["metaphor", "a metaphor"],
    choices: ["metaphor", "simile", "onomatopoeia", "pun"],
    explain: "It does not use like or as; it identifies the moon as a coin.",
  },
  {
    id: "e5",
    topic: "Writing",
    prompt: "A paragraph should usually contain…",
    answer: "one main idea",
    accepted: ["one main idea", "a main idea", "one idea"],
    choices: ["one main idea", "as many topics as possible", "only dialogue", "no topic sentence"],
    explain: "Clear paragraphs help the reader follow your argument or story.",
  },
  {
    id: "e6",
    topic: "Language techniques",
    prompt: "Repeating the same starting sound, as in bright birds beside the brook, is…",
    answer: "alliteration",
    accepted: ["alliteration"],
    choices: ["alliteration", "assonance", "irony", "pun"],
    explain: "Alliteration is the repetition of initial consonant sounds.",
  },
  {
    id: "e7",
    topic: "Writing",
    prompt: "The purpose of a topic sentence is to…",
    answer: "introduce the paragraph’s idea",
    accepted: ["introduce the paragraph’s idea", "introduce the idea", "state the main idea"],
    choices: ["introduce the paragraph’s idea", "end the essay", "list every example", "address the reader by name"],
    explain: "The topic sentence signs the idea; the rest of the paragraph develops it.",
  },
  {
    id: "e8",
    topic: "Narrative",
    prompt: "The atmosphere or feeling of a piece of writing is its…",
    answer: "mood",
    accepted: ["mood", "the mood"],
    choices: ["mood", "rhyme", "stanza", "caption"],
    explain: "Mood is the feeling created for the reader. Tone is the writer’s attitude.",
  },
];
