export const PHYS_TOPICS = [
  { id: "forces", name: "Forces", blurb: "Pushes, pulls, balanced and unbalanced." },
  { id: "energy", name: "Energy", blurb: "Stores, transfers, conservation." },
  { id: "waves", name: "Waves", blurb: "Light, sound, and wave properties." },
];

export const PHYS_QUESTIONS = [
  {
    id: "p1",
    topic: "Forces",
    prompt: "Force is measured in…",
    answer: "newtons",
    accepted: ["newtons", "newton", "n"],
    choices: ["newtons", "joules", "watts", "metres"],
    explain: "The newton (N) is the SI unit of force.",
  },
  {
    id: "p2",
    topic: "Forces",
    prompt: "If forces on an object are balanced, the object…",
    answer: "does not change its motion",
    accepted: ["does not change its motion", "stays at rest or steady speed", "no acceleration"],
    choices: ["does not change its motion", "must be stationary", "must speed up", "must change direction"],
    explain: "Balanced forces mean constant velocity — including remaining at rest.",
  },
  {
    id: "p3",
    topic: "Energy",
    prompt: "The unit of energy is the…",
    answer: "joule",
    accepted: ["joule", "joules", "j"],
    choices: ["joule", "newton", "watt", "volt"],
    explain: "Energy is measured in joules (J).",
  },
  {
    id: "p4",
    topic: "Energy",
    prompt: "Energy cannot be created or destroyed. This is the law of…",
    answer: "conservation of energy",
    accepted: ["conservation of energy", "energy conservation"],
    choices: ["conservation of energy", "gravity", "reflection", "moments"],
    explain: "Energy is transferred or stored in different ways, but the total stays the same.",
  },
  {
    id: "p5",
    topic: "Waves",
    prompt: "Sound cannot travel through…",
    answer: "a vacuum",
    accepted: ["a vacuum", "vacuum", "empty space"],
    choices: ["a vacuum", "air", "water", "metal"],
    explain: "Sound needs a medium. Light can travel through a vacuum.",
  },
  {
    id: "p6",
    topic: "Waves",
    prompt: "The distance from one wave crest to the next is the…",
    answer: "wavelength",
    accepted: ["wavelength", "the wavelength"],
    choices: ["wavelength", "amplitude", "frequency", "speed"],
    explain: "Wavelength is crest-to-crest (or trough-to-trough) distance.",
  },
  {
    id: "p7",
    topic: "Forces",
    prompt: "Friction usually…",
    answer: "opposes motion",
    accepted: ["opposes motion", "acts against movement", "slows things down"],
    choices: ["opposes motion", "increases speed", "creates energy", "removes gravity"],
    explain: "Friction acts in the opposite direction to the motion (or attempted motion).",
  },
  {
    id: "p8",
    topic: "Energy",
    prompt: "A moving object has…",
    answer: "kinetic energy",
    accepted: ["kinetic energy", "kinetic"],
    choices: ["kinetic energy", "gravitational potential only", "no energy", "chemical energy only"],
    explain: "Kinetic energy is the energy of motion.",
  },
];
