/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GardenRouteImport } from './routes/garden'
import { Route as PlayRouteImport } from './routes/play'
import { Route as ScholarRouteImport } from './routes/scholar'
import { Route as StudyRouteImport } from './routes/study'
import { Route as PlayIndexRouteImport } from './routes/play.index'
import { Route as PlayGameRouteImport } from './routes/play.$game'
import { Route as SessionKindRouteImport } from './routes/session.$kind'
import { Route as StudyIndexRouteImport } from './routes/study.index'
import { Route as StudySubjectRouteImport } from './routes/study.$subject'
import { Route as StudySubjectIndexRouteImport } from './routes/study.$subject.index'
import { Route as StudySubjectLearnRouteImport } from './routes/study.$subject.learn'
import { Route as StudySubjectPlayRouteImport } from './routes/study.$subject.play'
import { Route as StudySubjectPractiseRouteImport } from './routes/study.$subject.practise'
import { Route as StudySubjectProgressRouteImport } from './routes/study.$subject.progress'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GardenRoute = GardenRouteImport.update({
  id: '/garden',
  path: '/garden',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarRoute = ScholarRouteImport.update({
  id: '/scholar',
  path: '/scholar',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayRoute,
} as any)
const PlayGameRoute = PlayGameRouteImport.update({
  id: '/$game',
  path: '/$game',
  getParentRoute: () => PlayRoute,
} as any)
const SessionKindRoute = SessionKindRouteImport.update({
  id: '/session/$kind',
  path: '/session/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIndexRoute = StudyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudyRoute,
} as any)
const StudySubjectRoute = StudySubjectRouteImport.update({
  id: '/$subject',
  path: '/$subject',
  getParentRoute: () => StudyRoute,
} as any)
const StudySubjectIndexRoute = StudySubjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudySubjectRoute,
} as any)
const StudySubjectLearnRoute = StudySubjectLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => StudySubjectRoute,
} as any)
const StudySubjectPlayRoute = StudySubjectPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => StudySubjectRoute,
} as any)
const StudySubjectPractiseRoute = StudySubjectPractiseRouteImport.update({
  id: '/practise',
  path: '/practise',
  getParentRoute: () => StudySubjectRoute,
} as any)
const StudySubjectProgressRoute = StudySubjectProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => StudySubjectRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/garden': typeof GardenRoute
  '/play': typeof PlayRouteWithChildren
  '/scholar': typeof ScholarRoute
  '/study': typeof StudyRouteWithChildren
  '/play/$game': typeof PlayGameRoute
  '/session/$kind': typeof SessionKindRoute
  '/study/$subject': typeof StudySubjectRouteWithChildren
  '/play/': typeof PlayIndexRoute
  '/study/': typeof StudyIndexRoute
  '/study/$subject/learn': typeof StudySubjectLearnRoute
  '/study/$subject/play': typeof StudySubjectPlayRoute
  '/study/$subject/practise': typeof StudySubjectPractiseRoute
  '/study/$subject/progress': typeof StudySubjectProgressRoute
  '/study/$subject/': typeof StudySubjectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/garden': typeof GardenRoute
  '/scholar': typeof ScholarRoute
  '/play/$game': typeof PlayGameRoute
  '/session/$kind': typeof SessionKindRoute
  '/play': typeof PlayIndexRoute
  '/study': typeof StudyIndexRoute
  '/study/$subject/learn': typeof StudySubjectLearnRoute
  '/study/$subject/play': typeof StudySubjectPlayRoute
  '/study/$subject/practise': typeof StudySubjectPractiseRoute
  '/study/$subject/progress': typeof StudySubjectProgressRoute
  '/study/$subject': typeof StudySubjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/garden': typeof GardenRoute
  '/play': typeof PlayRouteWithChildren
  '/scholar': typeof ScholarRoute
  '/study': typeof StudyRouteWithChildren
  '/play/$game': typeof PlayGameRoute
  '/session/$kind': typeof SessionKindRoute
  '/study/$subject': typeof StudySubjectRouteWithChildren
  '/play/': typeof PlayIndexRoute
  '/study/': typeof StudyIndexRoute
  '/study/$subject/learn': typeof StudySubjectLearnRoute
  '/study/$subject/play': typeof StudySubjectPlayRoute
  '/study/$subject/practise': typeof StudySubjectPractiseRoute
  '/study/$subject/progress': typeof StudySubjectProgressRoute
  '/study/$subject/': typeof StudySubjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/garden'
    | '/play'
    | '/scholar'
    | '/study'
    | '/play/$game'
    | '/session/$kind'
    | '/study/$subject'
    | '/play/'
    | '/study/'
    | '/study/$subject/learn'
    | '/study/$subject/play'
    | '/study/$subject/practise'
    | '/study/$subject/progress'
    | '/study/$subject/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/garden'
    | '/scholar'
    | '/play/$game'
    | '/session/$kind'
    | '/play'
    | '/study'
    | '/study/$subject/learn'
    | '/study/$subject/play'
    | '/study/$subject/practise'
    | '/study/$subject/progress'
    | '/study/$subject'
  id:
    | '__root__'
    | '/'
    | '/garden'
    | '/play'
    | '/scholar'
    | '/study'
    | '/play/$game'
    | '/session/$kind'
    | '/study/$subject'
    | '/play/'
    | '/study/'
    | '/study/$subject/learn'
    | '/study/$subject/play'
    | '/study/$subject/practise'
    | '/study/$subject/progress'
    | '/study/$subject/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GardenRoute: typeof GardenRoute
  PlayRoute: typeof PlayRouteWithChildren
  ScholarRoute: typeof ScholarRoute
  StudyRoute: typeof StudyRouteWithChildren
  SessionKindRoute: typeof SessionKindRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garden': {
      id: '/garden'
      path: '/garden'
      fullPath: '/garden'
      preLoaderRoute: typeof GardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholar': {
      id: '/scholar'
      path: '/scholar'
      fullPath: '/scholar'
      preLoaderRoute: typeof ScholarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/$game': {
      id: '/play/$game'
      path: '/$game'
      fullPath: '/play/$game'
      preLoaderRoute: typeof PlayGameRouteImport
      parentRoute: typeof PlayRoute
    }
    '/session/$kind': {
      id: '/session/$kind'
      path: '/session/$kind'
      fullPath: '/session/$kind'
      preLoaderRoute: typeof SessionKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/': {
      id: '/study/'
      path: '/'
      fullPath: '/study/'
      preLoaderRoute: typeof StudyIndexRouteImport
      parentRoute: typeof StudyRoute
    }
    '/study/$subject': {
      id: '/study/$subject'
      path: '/$subject'
      fullPath: '/study/$subject'
      preLoaderRoute: typeof StudySubjectRouteImport
      parentRoute: typeof StudyRoute
    }
    '/study/$subject/': {
      id: '/study/$subject/'
      path: '/'
      fullPath: '/study/$subject/'
      preLoaderRoute: typeof StudySubjectIndexRouteImport
      parentRoute: typeof StudySubjectRoute
    }
    '/study/$subject/learn': {
      id: '/study/$subject/learn'
      path: '/learn'
      fullPath: '/study/$subject/learn'
      preLoaderRoute: typeof StudySubjectLearnRouteImport
      parentRoute: typeof StudySubjectRoute
    }
    '/study/$subject/play': {
      id: '/study/$subject/play'
      path: '/play'
      fullPath: '/study/$subject/play'
      preLoaderRoute: typeof StudySubjectPlayRouteImport
      parentRoute: typeof StudySubjectRoute
    }
    '/study/$subject/practise': {
      id: '/study/$subject/practise'
      path: '/practise'
      fullPath: '/study/$subject/practise'
      preLoaderRoute: typeof StudySubjectPractiseRouteImport
      parentRoute: typeof StudySubjectRoute
    }
    '/study/$subject/progress': {
      id: '/study/$subject/progress'
      path: '/progress'
      fullPath: '/study/$subject/progress'
      preLoaderRoute: typeof StudySubjectProgressRouteImport
      parentRoute: typeof StudySubjectRoute
    }
  }
}

interface PlayRouteChildren {
  PlayGameRoute: typeof PlayGameRoute
  PlayIndexRoute: typeof PlayIndexRoute
}

const PlayRouteChildren: PlayRouteChildren = {
  PlayGameRoute: PlayGameRoute,
  PlayIndexRoute: PlayIndexRoute,
}

const PlayRouteWithChildren = PlayRoute._addFileChildren(PlayRouteChildren)

interface StudySubjectRouteChildren {
  StudySubjectLearnRoute: typeof StudySubjectLearnRoute
  StudySubjectPlayRoute: typeof StudySubjectPlayRoute
  StudySubjectPractiseRoute: typeof StudySubjectPractiseRoute
  StudySubjectProgressRoute: typeof StudySubjectProgressRoute
  StudySubjectIndexRoute: typeof StudySubjectIndexRoute
}

const StudySubjectRouteChildren: StudySubjectRouteChildren = {
  StudySubjectLearnRoute: StudySubjectLearnRoute,
  StudySubjectPlayRoute: StudySubjectPlayRoute,
  StudySubjectPractiseRoute: StudySubjectPractiseRoute,
  StudySubjectProgressRoute: StudySubjectProgressRoute,
  StudySubjectIndexRoute: StudySubjectIndexRoute,
}

const StudySubjectRouteWithChildren = StudySubjectRoute._addFileChildren(
  StudySubjectRouteChildren,
)

interface StudyRouteChildren {
  StudySubjectRoute: typeof StudySubjectRouteWithChildren
  StudyIndexRoute: typeof StudyIndexRoute
}

const StudyRouteChildren: StudyRouteChildren = {
  StudySubjectRoute: StudySubjectRouteWithChildren,
  StudyIndexRoute: StudyIndexRoute,
}

const StudyRouteWithChildren = StudyRoute._addFileChildren(StudyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GardenRoute: GardenRoute,
  PlayRoute: PlayRouteWithChildren,
  ScholarRoute: ScholarRoute,
  StudyRoute: StudyRouteWithChildren,
  SessionKindRoute: SessionKindRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
